countryName = US
stateOrProvinceName = NY
localityName = NY
organizationName  = Akeyless
organizationalUnitName = Security
commonName = host1.leon.com

[ v3_req ]
basicConstraints = critical, CA:TRUE
keyUsage = critical, keyCertSign, cRLSign

