akeyless_url = "https://gw-aws.lm.cs.akeyless.fans/api/v2"
base_item_path = "/DLL-Signer/OpenSSL"
log_level = "debug"
use_classic_keys = false
[ksp]
signing_key_item = "/DLL-Signer/OpenSSL/dfc-sign-key"
signing_cert_item = "/DLL-Signer/OpenSSL/sign-cert"
[auth]
access_type = "access_key"
access_id = "p-g6ovtrot83dzam"
access_key = "VdDi2umCaIYEb5iVld15wDMSBn464korEupqxFrfs5w="
