cdakeyless_url = "https://gw-aws.lm.cs.akeyless.fans/api/v2"
base_item_path = "/DLL-Signer"
log_level = "debug"
use_classic_keys = false
[ksp]
signing_key_item = "/DLL-Signer/Cert-Signer-Key"
signing_cert_item = "/DLL-Signer/Cert/host1.leon.com"
[auth]
access_type = "cert"
access_id   = "p-525zk2ev76tycm"
cert_store_scope = "machine"
cert_store_name = "MY"
cert_store_sha1_thumbprint = "76CCC93BC784075FC1C49FE371AC71D120E83021"
